language: node_js
node_js:
  - "10.4"
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
script:
  - ng build --prod --aot
after_success:
  - firebase deploy -- project resume-site-46fc4 --token $FIREBASE_TOKEN