language: node_js
node_js:
  - "10.4"
branches:
  only:
    - master
deploy:
  skip_cleanup: true
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project resume-site-46fc4 --token $FIREBASE_TOKEN