language: node_js
node_js:
  - "10.4"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng build --prod --aot
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN