language: node_js
node_js:
  - node
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
  - npm install -g firebase-tools
script:
  - ng build --prod
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "resume-site-46fc4"